// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoG.Combat.Services.Api.Data;

#nullable disable

namespace WoG.Combat.Services.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240415220832_AddedEnumInsteadOfBool")]
    partial class AddedEnumInsteadOfBool
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WoG.Combat.Services.Api.Models.Duel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DefenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DuelOutcome")
                        .HasColumnType("int");

                    b.Property<long>("Ticks")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Duels");
                });
#pragma warning restore 612, 618
        }
    }
}
