// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoG.Combat.Services.Api.Data;

#nullable disable

namespace WoG.Combat.Services.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240416164659_HopefullyDone")]
    partial class HopefullyDone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WoG.Combat.Services.Api.Models.Duel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DefenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DuelOutcome")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Duels");
                });

            modelBuilder.Entity("WoG.Combat.Services.Api.Models.DuelEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<Guid>("DuelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<int>("Healing")
                        .HasColumnType("int");

                    b.Property<int>("InitialHealth")
                        .HasColumnType("int");

                    b.Property<int>("InitialMana")
                        .HasColumnType("int");

                    b.Property<int>("ManaSpent")
                        .HasColumnType("int");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeWhenNextActionOfTypeAvailable")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DuelId");

                    b.ToTable("DuelEvent");
                });

            modelBuilder.Entity("WoG.Combat.Services.Api.Models.DuelEvent", b =>
                {
                    b.HasOne("WoG.Combat.Services.Api.Models.Duel", null)
                        .WithMany("Events")
                        .HasForeignKey("DuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WoG.Combat.Services.Api.Models.Duel", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
