version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - '5673:5672'
      - '15673:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "3dg3Y0urB3ts"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"

  redis:
    image: redis:6.2-alpine
    entrypoint: redis-server --appendonly yes
    ports:
      - "6380:6379"
